### ISSUE TITLE
Add SQLite3

### ISSUE THREAD

**Issue by asterite** [rilut/awesome-crystal#1]
It's here:

https://github.com/manastech/crystal-sqlite3

**Comment by rilut** [comment]
@asterite Thanks! You could also make a pull request about `sqlite` in the Database Drivers section, between `crystal-redis` and `mongo.cr` if you want, I'll be happy to merge it. Or should I just add it myself?

**Comment by rilut** [comment]
@asterite By the way thank you for creating the Crystal lang!

**Comment by rilut** [comment]
@asterite Thanks! By the way thank you for creating the Crystal lang!
